name: CI

on:
  workflow_dispatch:
  push:
    tags:
      - 'prod-*'

jobs:
  build-windows:
    runs-on: [self-hosted, abitikku-windows]

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          $env:GITHUB_ACTIONS = $env:CI = $null
          make electron-develop
          make electron-build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-artifacts
          path: dist/*.exe

  build-linux:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14.16.0

      - name: Setup python
        run: pip install -r requirements.txt

      - name: Setup libudev
        run: sudo apt-get install libudev-dev

      - name: Build
        run: |
          unset GITHUB_ACTIONS CI
          sudo npm cache clean --force
          make electron-develop
          make electron-build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-artifacts
          path: |
            dist/*.AppImage
            dist/*.rpm
            dist/*.deb

  build-macos:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 14.16.0

      - name: Setup python
        run: pip install -r requirements.txt

      - name: Setup latest file command
        run: brew install file-formula

      - name: Build
        run: |
          unset GITHUB_ACTIONS CI
          export PATH="/usr/local/opt/file-formula/bin:$PATH"
          make electron-develop
          make electron-build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos-artifacts
          path: |
            dist/*.zip
            dist/*.dmg
            
  release:
    runs-on: ubuntu-latest
    needs: [build-windows,build-linux]
    
    steps:
      # Download previously shared builds
      - name: Get Linux artifact
        uses: actions/download-artifact@v1
        with:
          name: linux-artifacts
      - name: Get Windows artifact
        uses: actions/download-artifact@v1
        with:
          name: windows-artifacts
          
      - name: Copy artifacts to one dir
        run: rsync -a linux-artifact/ windows-artifacts/
          
      # Make official GitHub release which will trigger
      # sending the mail with link for access
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: windows-artifacts/*
          token: ${{ secrets.GITHUB_TOKEN }}
