name: CI

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: [self-hosted, abitikku-windows]

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          echo $env:PATH
          C:\msys\1.0\bin\make.exe electron-develop
          C:\msys\1.0\bin\make.exe electron-build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-artifacts
          path: dist/*.exe


  build-linux:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          architecture: x64
          node-version: v14.20.0

      - name: Install required packages
        run: |
          sudo apt install -y libudev-dev curl make

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          architecture: x64
          python-version: 2.7


      - name: Setup abitikku environment, test and build
        run: |
          git clone --recursive https://github.com/Testausserveri/abitikku.git abitikku_master
          cd abitikku_master

          git config --global url."https://github.com/".insteadOf git@github.com:
          git config --global url."https://".insteadOf git://

          C:\msys\1.0\bin\make.exe electron-develop
          npm test
          C:\msys\1.0\bin\make.exe electron-build


