name: CI

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: [self-hosted, abitikku-windows]

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          $env:GITHUB_ACTIONS = $env:CI = $null
          make electron-develop
          make electron-build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-artifacts
          path: dist/*.exe



